---
title: "STAT 413/613 HW 1"
author: "Yunting Chiu"
date: "`r Sys.Date()`"
output:
  html_document: 
    number_sections: true
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align  = "center",
                      fig.height = 4, 
                      fig.width  = 6)
```

# Instructions {-}

Admin elements:  
1. Upload a photo (headshot) of yourself into your canvas profile  
2. Review the Syllabus and the [academic integrity code](<https://www.american.edu/policies/students/upload/academic-integrity-code-2020.pdf>).  
3. Fill in your information in the Student Info spreadsheet under the Canvas Collaboration site.  

Analysis Elements: Rename the starter file under the analysis directory as `hw_01_yourname.Rmd` and use it for your solutions.   
1. Modify the "author" field in the YAML header.  
2. Stage and Commit R Markdown and HTML files (no PDF files).   
3. **Push both .Rmd and HTML files to GitHub**.   
- Make sure you have knitted to HTML prior to staging, committing, and pushing your final submission.  
4. **Commit each time you answer a part of question, e.g. 1.1**   
5. **Push to GitHub after each major question**, e.g., College Scorecard and World Bank Data   
- **Committing and Pushing are graded elements for this homework.**  
6. When complete, submit a response in Canvas  
    
- Only include necessary code to answer the questions.
- Most of the functions you use should be from the tidyverse. Too much base R will result in point deductions.
- Use Pull requests and or email to ask me any questions. If you email, please ensure your most recent code is pushed to GitHub.

# Learning Outcomes:  {-}
- Operate with Git and GitHub.
- Apply concepts and methods from STAT 412/612.   

# Canvas Picture, Syllabus, and Student Info
Review the Syllabus on Canvas and answer the following questions:

I, *enter your name*  have:

1. Added a photo of myself (headshot) to my Canvas profile

2. Reviewed the syllabus and the associated policies on the following date:

3. Reviewed the American University policies on academic integrity, and understand how they apply to this course and  agree to comply with them for this course

4. Filled in my information in the Student Info spreadsheet on Canvas collaborations

# College Scorecard

The data folder contains "college_score_200601.csv", a subset of the data in the [College Scorecard](https://collegescorecard.ed.gov/data/) database as of June 1, 2020. These data contain information on colleges in the United States. 
The variables include:

- `UNITID` and `OPEID`: Identifiers for the colleges.
- `INSTNM`: Institution name
- `ADM_RATE`: The Admission Rate.
- `SAT_AVE`: Average SAT equivalent score of students admitted.
- `UGDS`: Enrollment of undergraduate certificate/degree-seeking students
- `COSTT4_A`: Average cost of attendance (academic year institutions)
- `AVGFACSAL`: Average faculty salary
- `GRAD_DEBT_MDN`: The median debt for students who have completed
- `AGE_ENTRY`: Average age of entry
- `ICLEVEL`: Level of institution (1 = 4-year, 2 = 2-year, 3 = less than 2-year).
- `MN_EARN_WNE_P10`: Mean earnings of students working and not enrolled 10 years after entry.
- `MD_EARN_WNE_P10`: Median earnings of students working and not enrolled 10 years after entry.
- `FEMALE`: Share of female students
- `PCT_WHITE`: Percent of the population from students' zip codes that is White, via Census data


1. Use a relative path and a readr function to load the data from data/college_score_200601.csv into a tibble.
   
2. If you used the default settings for reading in the data, 11 variables are probably type character when they should be numeric. 
  + Which ones? 
  + Why were they read in as type character? 
 
3. Fix these variables to be numeric in the tibble.
 
4. How is average faculty salary associated the median earnings of students ten years after initial enrollment? Create an appropriate plot and interpret the plot to justify your answer.

5. Does the level of the institution seem to be associated with the median earnings of students ten years after enrollment? Reproduce this plot in R to explore this relationship and interpret the plot:
   
6. Plot the log of median earnings 10 years after enrollment for level 1 institutions as the Y axis against PCT_WHITE and, in a second plot, against FEMALE.  
- Describe the relationship if any in each of the plots.

7. Create a scatter plot of the log of mean earnings 10 years after enrollment (Y) axis) compared to the log of median earnings 10 years after enrollment (X axis).  
  + Include an abline. 
  + Interpret the plot.

8. Compute a ranking of level 1 universities based on the ratio of median earnings 10 years after enrollment compared to median graduation debt.   
  + Identify the top 5 best and the bottom 5 worst? 
  + What is American University's rank? 
- Extra Credit: 
  + Reproduce the following plot so the AU line adjusts as the data adjusts:
  + What is AU's new ranking if the mean earnings are used?
   
# World Bank Data

The World Bank provides loans to countries with the goal of reducing poverty. The dataframes in the data folder were taken from the public data repositories of the World Bank.

- country.csv: Contains information on the countries in the data set. 
  + The variables are:
    - `Country_Code`: A three-letter code for the country. Note not all rows are countries; some are regions.
    - `Region`: The region of the country.
    - `IncomeGroup`: Either `"High income"`, `"Upper middle income"`, `"Lower middle income"`, or `"Low income"`.
    - `TableName`: The full name of the country.  

- fertility.csv: Contains the fertility rate information for each country for each year. 
  + For the variables `1960` to `2017`, the values in the cells represent the fertility rate in total births per woman for that year. 
  + Total fertility rate represents the number of children that would be born to a woman if she were to live to the end of her  childbearing years and bear children in accordance with age-specific fertility rates of the specified year.   

- life_exp.csv: Contains the life expectancy information for each country for each year. 
  + For the variables `1960` to `2017`, the values in the cells represent life expectancy at birth in years for the given year. 
  + Life expectancy at birth indicates the number of years a newborn infant would live if prevailing patterns of mortality at the time of its birth were to stay the same throughout its life.  

- population.csv: Contains the population information for each country. 
  + For the variables `1960` to `2017`, the values in the cells represent the total population in number of people for the given year. 
  + Total population is based on the de facto definition of population, which counts all residents regardless of legal status or citizenship. The values shown are midyear estimates.

1. Use relative paths and a readr function to load these files into four tibbles.  

2. These data are messy. The observational units in `fert`, `life`, and `pop` are locations in space-time (e.g. Aruba in 2017). Recall tidy data should have one observational unit per row.  
  - Tidy these three tibbles.
  - Make sure the variable for `year` is a numeric.  

3. Combine the tibbles to create a new tibble which includes the fertility rate, population, and life expectancy in each year as well as the region for each country.

4. Make a scatterplot of fertility rate vs life expectancy, color-coding by region and annotating size by the population.  
  + Include only the years 1960, 1970, 1980, 1990, 2000, and 2010. 
  + Facet by these years.
  + Your final plot should look like this (Each element of the formatting is graded):
  + Hint: use `ggthemes`
  + **Interpret the plot in one sentence**.
   
5. Calculate the total population for each region for each year.  
  + Exclude 2018.  
  + Make a line plot of year versus log of total population, color-coding by region.
  + Your final plot should look like this:
  + **Interpret the plot in one sentence**.
   
6. Make a bar plot of population vs region for the year 2017.  
  + Order the bars on the $y$-axis in **decreasing** order of population. 
  + Your final plot should look like this:
 
 










