---
title: "STAT 413/613 HW 3: Lists and Iteration"
author: "YourName"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: yes
    toc: no
    toc_depth: 4
urlcolor: "blue"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align  = "center",
                      fig.height = 3, 
                      fig.width  = 5)
```

# Instructions {-}

1. Clone this homework repo to your homework directory as a new repo.
2. Rename the starter file under the analysis directory as `hw_01_yourname.Rmd` and use it for your solutions.   
3. Modify the "author" field in the YAML header.  
4. Stage and Commit R Markdown and HTML files (no PDF files).   
5. **Push both .Rmd and HTML files to GitHub**.   
- Make sure you have knitted to HTML prior to staging, committing, and pushing your final submission.  
6. **Commit each time you answer a part of question, e.g. 1.1**   
7. **Push to GitHub after each major question**   
8. When complete, submit a response in Canvas  
    
- Only include necessary code to answer the questions.
- Most of the functions you use should be from the tidyverse. Too much base R will result in point deductions.
- Use Pull requests and or email to ask me any questions. If you email, please ensure your most recent code is pushed to GitHub.

- Learning Outcomes:
    - Manipulate vectors in base-R syntax.
    - Apply iterations with for loops.

# Working with Lists

Because of their generality, lists (or list-like objects) are often the output of many statistical procedures in R. The file `fpout.RDS` in the data folder contains sample output from using [fitPoly](https://cran.r-project.org/package=fitPoly), a statistical
method to quantify properties of locations on the [genome](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5915555/).  

1. Use `readRDS()` and a relative path to read this data into R.

2. Use appropriate functions to obtain the length of the list and then the vector of the names from the list.

3. The `diploscores` element does not provide any information. Remove it from the list.
   
4. The `scores` element contains the output most users would want. The variables in `scores` called `P0`, `P1`, `P2`, `P3`, `P4`, `P5`, and `P6` contain "posterior probabilities" for each individual for values    `0`, `1`, `2`, `3`, `4`, `5`, and `6` (respectively).  
- A quantity useful in Bayesian analysis is called the "posterior mean," which in this case is calculated as follows:
  + posterior_mean = `(P0 * 0) + (P1 * 1) + (P2 * 2) + (P3 * 3) + (P4 * 4) + (P5 * 5) + (P6 * 6)`.
- Calculate the posterior mean for each individual and add this as a new variable in the `scores` data frame.

5. Use a `map*()` function to identify the names of the variables in the `scores` data frame that are *not* of type double.  
- Create a new element called `col_means` in the list that contains just the column means of all the *double* variables in the `scores` data frame.

6. Demonstrate three different ways to extract the `col_means` element from the list.  The extracted element should *not* be a list. 
- Show two ways to extract the third element of `col_means`

# For Loops

Consider the recursive sequence defined by
$$
x_n = x_{n-1} + \frac{|x_{n-3} - x_{n-2}|}{4}.
$$
That is, element $n$ is the sum of element $n-1$ and the absolute value of the difference between between elements $n-3$ and $n-2$ divided by two. For example, if we let $x_1 = 3$, $x_2 = 1$, and $x_3 = 10$, then $x_4$ is
$$
x_4 = 10 + \frac{|3 - 1|}{4} = 11.
$$

1. Write a function called `calcn()` that takes as input a vector `x` containing the first three elements of this sequence and an integer `n` denoting the final element of the sequence to calculate.  
- `calcn()` should return element `n`.
- Include error checking to to ensure the inputs are of the correct length and type and n is greater than 0.

For example, in my implementation of `calcn()`, I obtained the following: (see HTML)

- Evaluate your function at the following inputs:
  + calcn(c(11,1,130), 1000L)  
  + calcn(c(11,1,130), 1L)  
  + calcn(c(7, 3, 20), 8L)  

# Question: Lists, For-loops, and `map_*()`

Lists are often used to save simulation output. You can then extract individual elements from the lists using for-loops.

Consider the $t$-test, used to test whether or not the mean of some observations is 0. We would use the following code to simulate data from a [Normal (0,1) distribution](https://en.wikipedia.org/wiki/Normal_distribution), and then use a $t$-test to test if the true mean is 0:

1. The output of `t.test()` is a list-like object. Use one function to show how many elements are in the list along with their names and types.

2. Write a for-loop to perform the following three operations on iteration `i`:
    1. Draw 10 random observations from a normal distribution with mean 0 and standard deviation 2.
    2. Run a $t$-test on these 10 observations.
    3. Save the output of the $t$-test as the `i`th element in a list called `tlist`.  
    
- Set the seed to 1 and run for 1000 iterations.
    
3. Use the appropriate map function to extract the sample mean from each test (from 2) and pipe to an appropriate plot to show the sampling distribution of the sample mean.
- Hint: Make sure the data going into ggplot is a data frame (tibble)

4. The $p$-value is an important quantity in statistics. Use a for-loop to extract the $p$-values from each test in part 1 and combine these
   $p$-values into a single vector called `pvec_f`. Show the first 6 values.

5. Use the appropriate map function to extract the $p$-values from each test in part 1 and combine these $p$-values into a single vector called `pvec_m`. Show the first 6 values.

6. *Extra Credit* $p$-values have a nice property where, if the the null hypothesis is true (i.e. the mean of the observations is actually 0), then the $p$-values follow the uniform distribution. 

- Use the data from `pvec_m` to create a [QQ-plot](https://en.wikipedia.org/wiki/Q–Q_plot) and then interpret the plot with regard to whether the $p$-values exhibit a uniform distribution.  
- Ensure your plot has appropriate labels for the axes and a title. 
- Include an abline that is dashed and colored red.



